trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
  project-name-dev: 'opticca-demo'
  skip-creation: true

stages: 
- stage: Demo 
  displayName: Deploy DEV
  jobs:
  - job: Deploy
    displayName: Deploy-DEV-Job
    steps:
    
    - task: oc-setup@2
      displayName: Connect With OpenShift
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-service-connection'
        

    - task: oc-cmd@2
      displayName: Select DEV project
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-service-connection'
        cmd: 'oc project $(project-name-dev)'
        uselocalOc: true

    - task: oc-cmd@2
      displayName: Delete Web App
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-service-connection'
        cmd: 'oc delete all -l app=opticca-demo'
        uselocalOc: true

    - task: oc-cmd@2
      displayName: Deploy Web App
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-service-connection'
        cmd: 'oc new-app dotnet:6.0-ubi8~https://github.com/tsouzadev/OpticcaDemo --strategy=docker -l app=opticca-demo -e Server=20.118.144.28 -e Port=31433 -e Database=InnovationManagement -e User=sa -e Password=Sql2022Demo'
        uselocalOc: true

    - task: oc-cmd@2
      displayName: Expose Web App Service
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-service-connection'
        cmd: 'oc expose svc opticcademo'
        uselocalOc: true

    - task: oc-cmd@2
      displayName: Display Status
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift-service-connection'
        cmd: 'oc status'
        uselocalOc: true
